# Generated by Django 4.1.4 on 2022-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('owner', models.CharField(max_length=100)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('isDone', models.BooleanField(default=False, verbose_name='done status')),
            ],
        ),
    ]
